name: flutter_begin
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.2

# thêm thư viện
dependencies:
  font_awesome_flutter: ^10.8.0
  
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: edu
      fonts: 
        - asset: assets/fonts/edu.ttf
    
    - family: kapa
      fonts: 
        - asset: assets/fonts/kapa.ttf

  # định nghĩa đường dẫn load hình
  assets: 
    - assets/imgs/