name: flutter_endgame
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.8.0
  sqflite: ^2.4.2
  http: ^1.4.0
  socket_io_client: ^3.1.2
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5
  flutter_bloc: ^9.1.1
  device_info_plus: ^11.5.0
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  flutter_launcher_icons: ^0.14.4


  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter_launcher_icons:
  android: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true
